name: Add library to new flutter project
on:
  push:
  pull_request:
jobs:
  build-on-android-3-7-0:
    name: Build for android with 3.7.0 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=android
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build apk --debug
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-android-3-10-6:
    name: Build for android with 3.10.6 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=android
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build apk --debug
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-ios-3-7-0:
    name: Build for ios with 3.7.0 on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=ios
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build ios --release --no-codesign
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-ios-3-10-6:
    name: Build for ios with 3.10.6 on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=ios
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build ios --release --no-codesign
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-web-3-7-0:
    name: Build for web with 3.7.0 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=web
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build web --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-web-3-10-6:
    name: Build for web with 3.10.6 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=web
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build web --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-linux-3-7-0:
    name: Build for linux with 3.7.0 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=linux
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build linux --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-linux-3-10-6:
    name: Build for linux with 3.10.6 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=linux
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build linux --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-macos-3-7-0:
    name: Build for macos with 3.7.0 on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=macos
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-macos-3-10-6:
    name: Build for macos with 3.10.6 on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=macos
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-windows-3-7-0:
    name: Build for windows with 3.7.0 on windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=windows
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"..\\"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-windows-3-10-6:
    name: Build for windows with 3.10.6 on windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=windows
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"..\\"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
