name: Add library to new flutter project
on:
  push:
  pull_request:
jobs:
  build-on-android-3-7-0:
    name: Build flutter for android on ubuntu-latest with 3.7.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=android
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build apk --debug
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-android-3-10-6:
    name: Build flutter for android on ubuntu-latest with 3.10.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=android
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build apk --debug
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-ios-3-7-0:
    name: Build flutter for ios on macos-latest with 3.7.0
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=ios
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build ios --release --no-codesign
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-ios-3-10-6:
    name: Build flutter for ios on macos-latest with 3.10.6
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=ios
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build ios --release --no-codesign
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-web-3-7-0:
    name: Build flutter for web on ubuntu-latest with 3.7.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=web
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build web --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-web-3-10-6:
    name: Build flutter for web on ubuntu-latest with 3.10.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=web
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build web --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-linux-3-7-0:
    name: Build flutter for linux on ubuntu-latest with 3.7.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.1'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=linux
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build linux --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-linux-3-10-6:
    name: Build flutter for linux on ubuntu-latest with 3.10.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.1'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=linux
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build linux --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-macos-3-7-0:
    name: Build flutter for macos on macos-latest with 3.7.0
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=macos
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-macos-3-10-6:
    name: Build flutter for macos on macos-latest with 3.10.6
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=macos
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-windows-3-7-0:
    name: Build flutter for windows on windows-latest with 3.7.0
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=windows
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-windows-3-10-6:
    name: Build flutter for windows on windows-latest with 3.10.6
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=windows
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../"}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
