name: Add library to new flutter project
on:
  push:
  pull_request:
jobs:
  build-on-windows-3-7-0:
    name: Build flutter for windows on windows-latest with 3.7.0
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.0
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=windows
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../."}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-on-windows-3-10-6:
    name: Build flutter for windows on windows-latest with 3.10.6
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=windows
        name: Create new project
      - name: Add adaptation to new project.
        run: flutter pub add -- 'adaptation:{"path":"../."}'
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
