name: Add library to new flutter project

on:
  push:
  pull_request:

jobs:
  build-on-ios:
    name: flutter build on ios with ${{ matrix.flutter-version }}
    runs-on: macos-latest
    strategy:
      matrix:
        flutter-version: ['3.10.6', '3.7.0']
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=ios
        name: Create new project
      - run: flutter pub add -- 'adaptation:{"path":"${{ github.workspace }}"}'
        working-directory: ${{ github.workspace }}/new_project
        name: Add package to new project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build ios --release --no-codesign
        working-directory: ${{ github.workspace }}/new_project
        name: Build example

  build-on-android:
    name: flutter build on android with ${{ matrix.flutter-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: ['3.10.6', '3.7.0']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=android
        name: Create new project
      - run: flutter pub add -- 'adaptation:{"path":"${{ github.workspace }}"}'
        working-directory: ${{ github.workspace }}/new_project
        name: Add package to new project
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build apk --debug
        working-directory: ${{ github.workspace }}/new_project
        name: Build example

